version: "3.1"

services:

  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: projeto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "15433:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
